project_id = "nbkybwnjjzmwyiiciffm"

[auth]
enabled = true
site_url = "https://nbkybwnjjzmwyiiciffm.lovableproject.com"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.list-active-coupons]
verify_jwt = true

[functions.send-draw-reminder]
verify_jwt = true

[functions.send-new-data-alert]
verify_jwt = true

[functions.update-promo-code]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

